services:
  - type: web
    name: sahaay-setu
    env: python
    repo: https://github.com/kanishkayush/Sahaay-Setu-
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: ENVIRONMENT
        value: production
      - key: PERSISTENT_DATA_DIR
        value: /data
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
