#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Mirror Open Design's generated screens into design/ inside this repo.
#
# Open Design writes to its own sandbox under Application Support, which is
# invisible to git, to reviewers, and to any agent working in this repo. This
# pulls that output in so the design language is versioned alongside the code
# it is meant to change.
#
#   bash .agents/sync-design.sh          one-shot sync
#   bash .agents/sync-design.sh --check  print the source checksum and exit
#
# The mirror is READ-ONLY output. Never hand-edit design/ — edit in Open Design
# and re-sync, or the next run silently overwrites you.
# ---------------------------------------------------------------------------
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$REPO_ROOT/design"
OD_DATA="$HOME/Library/Application Support/Open Design/namespaces/release-stable/data"

# Resolve the most recently modified project rather than hardcoding an id —
# a new Open Design project gets a new uuid.
resolve_source() {
  [[ -d "$OD_DATA/projects" ]] || return 1
  find "$OD_DATA/projects" -maxdepth 1 -mindepth 1 -type d -print0 2>/dev/null \
    | xargs -0 -I{} stat -f '%m %N' {} 2>/dev/null \
    | sort -rn | head -1 | cut -d' ' -f2-
}

SRC="$(resolve_source || true)"
if [[ -z "${SRC:-}" || ! -d "$SRC" ]]; then
  echo "No Open Design project found under $OD_DATA/projects" >&2
  exit 2
fi

# Checksum of every tracked design file — the change signal for the watcher.
checksum() {
  find "$SRC" -type f \( -name '*.html' -o -name '*.css' -o -name '*.js' \) \
    -not -path '*/.*/*' -print0 2>/dev/null \
    | sort -z | xargs -0 shasum 2>/dev/null | shasum | cut -d' ' -f1
}

if [[ "${1:-}" == "--check" ]]; then
  checksum
  exit 0
fi

mkdir -p "$DEST"
# Filter order matters: rsync takes the first match, so excludes come first.
# Exclude every dot-directory rather than naming them one by one — Open Design
# keeps its own scaffolding and version store alongside the output
# (.od-skills/, .file-versions/, and whatever it adds next), and none of that
# belongs in the repo.
# README.md is ours, not Open Design's. rsync protects excluded destination
# files from --delete, but state it explicitly so adding --delete-excluded
# later cannot silently wipe it.
rsync -a --delete \
  --filter='protect README.md' \
  --exclude='.*/' \
  --include='*/' \
  --include='*.html' --include='*.css' --include='*.js' \
  --exclude='*' \
  --prune-empty-dirs \
  "$SRC/" "$DEST/" 2>/dev/null

# Idempotent: if the content checksum is unchanged, leave MANIFEST.json alone.
# Open Design's critique stage sometimes rewrites a file and reverts it between
# polls; without this, each flap rewrites syncedAt and dirties git for nothing.
NEW_SUM="$(checksum)"
OLD_SUM="$(python3 -c "import json;print(json.load(open('$DEST/MANIFEST.json'))['checksum'])" 2>/dev/null || echo none)"
if [[ "$NEW_SUM" == "$OLD_SUM" ]]; then
  echo "No design changes (checksum ${NEW_SUM:0:12}) — mirror already current"
  exit 0
fi

FILES=$(find "$DEST" -type f \( -name '*.html' -o -name '*.css' -o -name '*.js' \) | wc -l | tr -d ' ')
BYTES=$(find "$DEST" -type f \( -name '*.html' -o -name '*.css' -o -name '*.js' \) -exec stat -f '%z' {} + 2>/dev/null | awk '{s+=$1} END {print s+0}')

cat > "$DEST/MANIFEST.json" <<EOF
{
  "_comment": "Generated by .agents/sync-design.sh — do not edit design/ by hand. Deliberately contains no timestamp: the manifest is a pure function of the design content, so a no-op sync leaves the tree clean. Git history records when each change landed.",
  "source": "Open Design ($(basename "$SRC"))",
  "checksum": "$NEW_SUM",
  "fileCount": $FILES,
  "totalBytes": $BYTES,
  "screens": [
$(find "$DEST/screens" -name '*.html' 2>/dev/null | sort | sed 's|.*/||' | sed 's/^/    "/;s/$/",/' | sed '$ s/,$//')
  ]
}
EOF

echo "Synced $FILES files ($((BYTES / 1024)) KB) from $(basename "$SRC") -> design/"
